# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mysql:
    container_name: flask_mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: fornecedordb
    ports:
      - "61441:61441"
      - "3306:3306"
    expose:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - myconnection
  minimalapi:
    image: minimalapi
    build:
      context: .
      dockerfile: MinimalApi/Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - mysql
    networks:
      - myconnection
    command: ["dotnet", "ef", "database update"]
volumes:
  dbdata:
networks:
  myconnection:
    driver: bridge
